apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-world-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-world
  template:
    metadata:
      labels:
        app: app-world
    spec:
      containers:
        - name: app-world
          image: marjio0/app-world:latest
          ports:
            - containerPort: 3000
